version: "3"
services:
    predictions_api:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./server.py:/app/server.py:ro
            - ./config.yml:/app/config.yml:ro
            - ./modules:/app/modules:ro

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - predictions_api
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ros

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        depends_on:
            - predictions_api
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - --config.file=/etc/prometheus/prometheus.yml
