version: "3"
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - predictions_api
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        depends_on:
            - predictions_api
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - --config.file=/etc/prometheus/prometheus.yml

    predictions_api:
        build: ./api
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app:ro
