version: "3"
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"

        # for development
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - --config.file=/etc/prometheus/prometheus.yml

    predictions_api:
        build: ./api
        ports:
            - "8000:8000"

        # for development
        volumes:
            - ./api:/app

    test:
        build: ./prometheus

        # for development
        volumes:
            - ./prometheus/test.py:/app/test.py:ro
