version: "3"
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"

        # for development
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    fastapi_app:
        build: ./api
        ports:
            - "8000:8000"

        # for development
        volumes:
            - ./api:/app:ro
